=== adiwg/mdJson-schemas/schema/processStep.json
{
    "id": "processStep.json#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "description": "Information on the history of the resource.",
    "example": "../examples/processStep.json",
    "translation": {
        "ISO 19115-2": [
            "LI_Lineage"
        ]
    },
    "properties": {
        "stepId": {
            "type": "string",
            "description": "Serial identifier used to order the sequence of steps used.",
            "translation": {
                "ISO 19115-2": [
                    "LI_ProcessStep @ id"
                ]
            }
        },
        "description": {
            "type": "string",
            "description": "Description of the process or methodology step.",
            "translation": {
                "ISO 19115-2": [
                    "LI_ProcessStep > description"
                ],
                "FGDC CSDGM": [
                    "dataqual > lineage > procstep > procdesc"
                ]
            }
        },
        "rationale": {
            "type": "string",
            "description": "Requirement or purpose for the process or methodology step.",
            "translation": {
                "ISO 19115-2": [
                    "LI_ProcessStep > rationale"
                ]
            }
        },
        "timePeriod": {
            "description": "Date, datetime, or period at which the process or methodology step occurred.",
            "translation": {
                "ISO 19115-2": [
                    "LI_ProcessStep > dateTime"
                ],
                "FGDC CSDGM": [
                    "dataqual > lineage > procstep > procdate"
                ]
            },
            "$ref": "./timePeriod.json#"
        },
        "processor": {
            "type": "array",
            "description": "Identification of, and means of communication with, person(s) and organization(s) associated with the process or methodology step.",
            "translation": {
                "ISO 19115-2": [
                    "LI_ProcessStep > processor > CI_ResponsibleParty"
                ],
                "FGDC CSDGM": [
                    "dataqual > lineage > procstep > proccont > cntinfo"
                ]
            },
            "items": {
                "$ref": "./responsibility.json#"
            }
        },
        "stepSource": {
            "type": "array",
            "description": "Information about the source data used in the process step.",
            "translation": {
                "ISO 19115-2": [
                    "DQ_DataQuality > LI_Lineage > LI_ProcessStep > LI_source"
                ],
                "FGDC CSDGM": [
                    "dataqual > lineage > procstep > srcused"
                ]
            },
            "items": {
                "$ref": "./source.json#"
            }
        },
        "stepProduct": {
            "type": "array",
            "description": "Information about an intermediate data set that (1) is significant in the opinion of the data producer, (2) is generated in the processing step, and (3) is used in later processing steps.",
            "translation": {
                "ISO 19115-2": [
                    "DQ_DataQuality > LI_Lineage > LI_ProcessStep > LI_source"
                ],
                "FGDC CSDGM": [
                    "dataqual > lineage > procstep > srcprod"
                ]
            },
            "items": {
                "$ref": "./source.json#"
            }
        },
        "reference": {
            "type": "array",
            "description": "Citation for process step documentation.",
            "translation": {},
            "items": {
                "$ref": "./citation.json#"
            }
        },
        "scope": {
            "$ref": "./scope.json#",
            "description": "Type of resource and/or extent to which the process information.",
            "translation": {}
        },
        "processingInformation": {
            "$ref": "./processing.json#",
            "description": "comprehensive information about the procedure by which the algorithm was applied to derive geographic data from the raw instrument measurements, such as datasets, software used, and the processing environment"
        },
        "report": {
            "type": "array",
            "items": {
                "$ref": "./processStepReport.json#"
            },
            "description": "report generated by the process step"
        }
    }
}

=== adiwg/mdJson-schemas/examples/processStep.json
[{
  "stepId": "stepId",
  "description": "description",
  "rationale": "rationale",
  "timePeriod": {
    "startDateTime": "2016-10-15"
  },
  "processor": [{
      "role": "role",
      "roleExtent": [{
        "temporalExtent": [{
          "timePeriod": {
            "startDateTime": "2016-10-24T11:10:15.2-10:00"
          }
        }]
      }],
      "party": [{
        "contactId": "individualId0"
      }]
    },
    {
      "role": "role",
      "roleExtent": [{
        "temporalExtent": [{
          "timePeriod": {
            "startDateTime": "2016-10-24T11:10:15.2-10:00"
          }
        }]
      }],
      "party": [{
        "contactId": "individualId0"
      }]
    }
  ],
  "stepSource": [{
    "description": "description",
    "sourceCitation": {
      "title": "title"
    },
    "metadataCitation": [{
      "title": "title"
    }, {
      "title": "title"
    }],
    "spatialResolution": {
      "measure": {
        "type": "distance",
        "value": 99.9,
        "unitOfMeasure": "unitOfMeasure"
      }
    },
    "referenceSystem": {
      "referenceSystemType": "referenceSystemType",
      "referenceSystemIdentifier": {
        "identifier": "identifier"
      }
    },
    "sourceProcessStep": [{
      "description": "description"
    }, {
      "description": "description"
    }]
  }],
  "stepProduct": [{
    "description": "description",
    "sourceCitation": {
      "title": "title"
    },
    "metadataCitation": [{
      "title": "title"
    }, {
      "title": "title"
    }],
    "spatialResolution": {
      "measure": {
        "type": "distance",
        "value": 99.9,
        "unitOfMeasure": "unitOfMeasure"
      }
    },
    "referenceSystem": {
      "referenceSystemType": "referenceSystemType",
      "referenceSystemIdentifier": {
        "identifier": "identifier"
      }
    },
    "sourceProcessStep": [{
      "description": "description"
    }, {
      "description": "description"
    }]
  }],
  "reference": [{
      "title": "title"
    },
    {
      "title": "title"
    }
  ],
  "processingInformation": { },
  "report": [ ]
}]
