=== adiwg/mdJson-schemas/schema/schema.json
{
  "id": "schema.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "2.9.6",
  "description": "schema for ADIwg mdJSON metadata",
  "example": "../examples/mdJson.json",
  "type": "object",
  "required": ["schema", "contact"],
  "properties": {
    "schema": {
      "$ref": "#/definitions/schema"
    },
    "contact": {
      "type": "array",
      "description": "An array of contacts to be referenced throughout the metadata. Any contact used in the metadata record must be stored within this array and referenced by contactId. Items in array may be used 0-n times throughout the record.",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "contact.json"
      }
    },
    "metadata": {
      "$ref": "metadata.json"
    },
    "metadataRepository": {
      "type": "array",
      "description": "Identifies repositories for distribution of the resource metadata.",
      "uniqueItems": true,
      "items": {
        "$ref": "metadataRepository.json"
      }
    },
    "dataDictionary": {
      "type": "array",
      "description": "A description of the contents, format and structure of the physical objects in a data resource.",
      "translation": {
        "ISO 19115-2": ["FC_FeatureCatalogue"]
      },
      "example": "../examples/dataDictionary.json",
      "items": {
        "$ref": "dataDictionary.json"
      }
    }
  },
  "definitions": {
    "schema": {
      "type": "object",
      "description": "Identifies the version of the JSON schema standard that applies to the metadata.",
      "required": ["name", "version"],
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string",
          "description": "Schema identifier, i.e. the name of the schema standard."
        },
        "version": {
          "type": "string",
          "description": "Specific version number of the schema standard.",
          "pattern": "[0-9]\\.[0-9]\\.[0-9]"
        }
      }
    }
  }
}

=== adiwg/mdJson-schemas/examples/mdJson.json
{
  "schema": {
    "name": "mdJson",
    "version": "2.6.0"
  },
  "contact": [{
      "contactId": "CID001",
      "isOrganization": false,
      "name": "Stan Smith",
      "positionName": "Associate - retired",
      "memberOfOrganization": [
        "CID002",
        "CID003"
      ],
      "logoGraphic": [{
          "fileName": "fileName0",
          "fileDescription": "fileDescription0",
          "fileType": "fileType0",
          "fileConstraint": [{
              "type": "use",
              "useLimitation": [
                "useLimitation0",
                "useLimitation1"
              ]
            },
            {
              "type": "legal",
              "legal": {
                "useConstraint": [
                  "useConstraint0",
                  "useConstraint1"
                ],
                "accessConstraint": [
                  "accessConstraint0",
                  "accessConstraint1"
                ],
                "otherConstraint": [
                  "otherConstraint0",
                  "otherConstraint1"
                ]
              }
            },
            {
              "type": "security",
              "security": {
                "classification": "classification",
                "classificationSystem": "classificationSystem",
                "userNote": "userNote",
                "handlingDescription": "handlingDescription"
              }
            }
          ],
          "fileUri": [{
            "uri": "http://ISO.uri/adiwg/0"
          }]
        },
        {
          "fileName": "fileName1",
          "fileDescription": "fileDescription1",
          "fileType": "fileType1"
        },
        {
          "fileName": "fileName2"
        }
      ],
      "phone": [{
          "phoneName": "mobile",
          "phoneNumber": "111-111-1111",
          "service": [
            "voice",
            "sms",
            "message"
          ]
        },
        {
          "phoneName": "office",
          "phoneNumber": "222-222-2222",
          "service": [
            "voice",
            "message"
          ]
        }
      ],
      "address": [{
          "addressType": [
            "mailing",
            "physical"
          ],
          "description": "work location",
          "deliveryPoint": [
            "address line 1",
            "address line 2"
          ],
          "city": "city",
          "administrativeArea": "state",
          "postalCode": "zip",
          "country": "country"
        },
        {
          "addressType": [
            "mailing"
          ],
          "description": "telework location",
          "deliveryPoint": [
            "address line 3"
          ],
          "city": "city",
          "administrativeArea": "state",
          "postalCode": "zip",
          "country": "country"
        }
      ],
      "electronicMailAddress": [
        "e.mail@address.com1",
        "e.mail@address.com2"
      ],
      "onlineResource": [{
          "uri": "http://ISO.uri/adiwg/1",
          "protocol": "protocol",
          "name": "name",
          "description": "description",
          "function": "function"
        },
        {
          "uri": "http://ISO.uri/adiwg/2"
        }
      ],
      "hoursOfService": [
        "hoursOfService1",
        "hoursOfService2"
      ],
      "contactInstructions": "contactInstructions",
      "contactType": "individual"
    },
    {
      "contactId": "CID002",
      "isOrganization": true,
      "name": "US Geological Survey",
      "memberOfOrganization": [
        "CID005"
      ],
      "logoGraphic": [{
        "fileName": "fileName"
      }],
      "phone": [{
        "phoneName": "single service",
        "phoneNumber": "111-111-1111",
        "service": [
          "voice"
        ]
      }],
      "address": [{
        "addressType": [
          "addressType"
        ],
        "city": "Anchorage",
        "administrativeArea": "AK",
        "postalCode": "99508"
      }],
      "electronicMailAddress": [
        "e.mail@address.com2"
      ],
      "onlineResource": [{
        "uri": "http://ISO.uri/adiwg/2"
      }],
      "hoursOfService": [
        "hoursOfService"
      ],
      "contactInstructions": "contactInstructions",
      "contactType": "federal"
    },
    {
      "contactId": "CID003",
      "isOrganization": true,
      "name": "Arctic Landscape Conservation Cooperative",
      "contactType": "federal",
      "phone": [{
        "phoneName": "single service",
        "phoneNumber": "111-111-1111",
        "service": [
          "voice"
        ]
      }],
      "address": [{
        "addressType": [
          "addressType"
        ],
        "city": "Anchorage",
        "administrativeArea": "AK",
        "postalCode": "99508"
      }]
    },
    {
      "contactId": "CID004",
      "isOrganization": false,
      "name": "Joshua Bradley",
      "positionName": "Data Manager",
      "memberOfOrganization": [
        "CID003"
      ],
      "phone": [{
        "phoneName": "single service",
        "phoneNumber": "111-111-1111",
        "service": [
          "voice"
        ]
      }],
      "address": [{
        "addressType": [
          "addressType"
        ],
        "city": "Anchorage",
        "administrativeArea": "AK",
        "postalCode": "99508"
      }]
    },
    {
      "contactId": "CID005",
      "isOrganization": true,
      "name": "US Department of the Interior",
      "contactType": "federal"
    },
    {
      "contactId": "CID006",
      "isOrganization": false,
      "name": "Dennis Walworth",
      "memberOfOrganization": [
        "CID002"
      ],
      "contactType": "individual",
      "phone": [{
        "phoneName": "single service",
        "phoneNumber": "111-111-1111",
        "service": [
          "voice"
        ]
      }],
      "address": [{
        "addressType": [
          "addressType"
        ],
        "city": "Anchorage",
        "administrativeArea": "AK",
        "postalCode": "99508"
      }]
    }
  ],
  "metadata": {
    "metadataInfo": {
      "metadataIdentifier": {
        "identifier": "e9e82406-8308-4231-98e3-8b70fd438ada",
        "namespace": "https://www.uuidgenerator.net/",
        "version": "version 1.0",
        "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        "authority": {
          "title": "Metadata Identifier Authority Title",
          "alternateTitle": [
            "alternateTitle0",
            "alternateTitle1"
          ]
        }
      },
      "parentMetadata": {
        "title": "Metadata Authority Title",
        "alternateTitle": [
          "alternateTitle0",
          "alternateTitle1"
        ],
        "date": [{
            "date": "2016-10-13",
            "dateType": "dateType0"
          },
          {
            "date": "2016-10-22T16:15:14",
            "dateType": "dateType1"
          }
        ],
        "edition": "edition",
        "responsibleParty": [{
            "role": "principalInvestigator",
            "roleExtent": [{
                "description": "Extent 1: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
              },
              {
                "description": "Extent 2: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
                "geographicExtent": [{
                  "containsData": true,
                  "geographicElement": [{
                    "type": "Feature",
                    "id": "polygon-75",
                    "bbox": [-10.0, -10.0,
                      10.0,
                      10.0
                    ],
                    "geometry": {
                      "type": "Polygon",
                      "coordinates": [
                        [
                          [-161.74223,
                            67.663378
                          ],
                          [-161.440345,
                            67.630173
                          ],
                          [-161.294611,
                            67.656257
                          ],
                          [-161.228063,
                            67.625736
                          ],
                          [-161.247712,
                            67.585909
                          ],
                          [-161.334662,
                            67.591324
                          ],
                          [-161.566245,
                            67.491263
                          ],
                          [-161.812338,
                            67.455299
                          ],
                          [-161.825019,
                            67.40123
                          ],
                          [-162.128301,
                            67.414364
                          ],
                          [-162.167825,
                            67.363047
                          ],
                          [-162.383403,
                            67.293329
                          ],
                          [-162.633432,
                            67.272237
                          ],
                          [-162.645587,
                            67.356665
                          ],
                          [-162.369023,
                            67.455264
                          ],
                          [-162.287324,
                            67.551235
                          ],
                          [-162.171139,
                            67.559356
